branches: [main]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: docker tag dev.local/veraid-authority ghcr.io/relaycorp/veraid-authority:${nextRelease.version}
      publishCmd: docker push ghcr.io/relaycorp/veraid-authority:${nextRelease.version}
  - - "@semantic-release/exec"
  - - "@semantic-release/github"
    - assets:
        - path: k8s/*.yml
