apiVersion: skaffold/v1
kind: Config
metadata:
  name: getting-started-knative
build:
  artifacts:
    - image: dev.local/veraid-authority
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/service.yml
