apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: veraid-authority-awala
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: awala
          image: dev.local/veraid-authority
          args: [awala]
          env:
            - name: AUTHORITY_VERSION
              value: "1.0.0dev1"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongodb_password

            # Mock AWS KMS (used by WebCrypto KMS)
            - name: KMS_ADAPTER
              value: AWS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: aws_kms_secret_access_key
            - name: AWS_KMS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: mock-aws-kms
                  key: endpoint
            - name: AWS_KMS_REGION
              value: eu-west-2

            - name: CE_CHANNEL_AWALA_OUTGOING_MESSAGES
              value: http://mock-awala-middleware.default
            - name: CE_CHANNEL_BACKGROUND_QUEUE
              value: http://veraid-authority-queue.default
          envFrom:
            - configMapRef:
                name: mongodb
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
