apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mock-aws-kms
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: mock-aws-kms
          image: nsmithuk/local-kms:3.11.4
