apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mock-authz-server
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: mock-oauth2-server
          image: ghcr.io/navikt/mock-oauth2-server:0.5.8
          readinessProbe:
            httpGet:
              path: /default/.well-known/openid-configuration
