apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: veraid-authority
spec:
  template:
    spec:
      containers:
        - name: authority-server
          image: dev.local/veraid-authority
          args:
            - build/main/bin/server.js
          readinessProbe:
            httpGet:
              path: /
          env:
            - name: AUTHORITY_VERSION
              value: "1.0.0dev1"
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: credentials
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongodb_password
            - name: MONGODB_URI
              value: mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb
