apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: veraid-authority
spec:
  template:
    spec:
      containers:
        - name: authority-server
          image: dev.local/veraid-authority
          args: [api]
          readinessProbe:
            httpGet:
              path: /
          env:
            - name: AUTHORITY_VERSION
              value: "1.0.0dev1"
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: credentials
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongodb_password
            - name: MONGODB_URI
              value: mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb

            - name: OAUTH2_JWKS_URL
              value: http://mock-authz-server.default/default/jwks
            - name: OAUTH2_TOKEN_AUDIENCE
              value: default
            - name: OAUTH2_TOKEN_ISSUER_REGEX
              value: ^http://[^/]+/default$

            # Mock AWS KMS (used by WebCrypto KMS)
            - name: KMS_ADAPTER
              value: AWS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: credentials
                  key: aws_kms_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: aws_kms_secret_access_key
            - name: AWS_KMS_ENDPOINT
              value: http://mock-aws-kms:8080
            - name: AWS_KMS_REGION
              value: eu-west-2
