title: VeraId Authority

markdown: kramdown

baseurl: /veraid-authority
destination: ../build/docs
remote_theme: pmarsceill/just-the-docs@v0.2.7-r

footer_content: "Copyright &copy; 2023-2025 by Relaycorp, Inc."

aux_links:
  GitHub repository:
    - https://github.com/relaycorp/veraid-authority

color_scheme: dark

search_enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
