name: CI and automated releases
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-compose-ci.yml@main
    with:
      docker_image_local_name: veraid-authority
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/server-release.yml@main
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_PUSH_PASSWORD }}
