name: CI and automated releases
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-knative-ci.yml@main
    with:
      docker_image_local_name: dev.local/veraid-authority
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      kubernetes_app_name: veraid-authority
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-knative-release.yml@main
