name: CI and automated releases
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-knative-ci.yml@main
    with:
      docker_image_local_name: dev.local/veraid-authority

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-knative-release.yml@main
    secrets:
      ghcr_password: ${{ secrets.GH_CONTAINER_REGISTRY_PASSWORD }}
