name: CI and automated releases
on:
  pull_request:
jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Create Kind cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: default
          kubectl_version: "v1.25.3"
      - name: Setup kn
        run: |-
          set -o nounset
          set -o errexit
          set -o pipefail

          set -x

          sudo wget --quiet -O "${BIN_PATH}/kn" "https://github.com/knative/client/releases/download/knative-v$KN_VERSION/kn-linux-amd64"
          sudo chmod +x "${BIN_PATH}/kn"

          sudo wget --quiet -O "${BIN_PATH}/kn-quickstart" "https://github.com/knative-sandbox/kn-plugin-quickstart/releases/download/knative-v$KN_VERSION/kn-quickstart-linux-amd64"
          sudo chmod +x "${BIN_PATH}/kn-quickstart"

          kn quickstart --help
        env:
          KN_VERSION: "1.9.0"
          BIN_PATH: /home/runner/.local/bin
